export const categorias = [
  { id: 1, label: "Cupón" },
  { id: 2, label: "Feedback" },
  { id: 3, label: "Listado de enlaces" },
  { id: 4, label: "Ruleta" },
  { id: 5, label: "Página web" },
  { id: 6, label: "Tarjeta de fidelidad" },
  { id: 7, label: "Vcard Plus" },
  { id: 8, label: "Cartel Google" },
  { id: 9, label: "Cartel WhatsApp" },
  { id: 10, label: "Cartel Tripadvisor" },
  { id: 11, label: "Cartel Facebook" },
  { id: 12, label: "Cartel Instagram" },
  { id: 13, label: "Cartel Brubank" },
  { id: 14, label: "Cartel TikTok" },
  { id: 15, label: "Cartel Menú" },
  { id: 16, label: "Tarjeta de Google" },
  { id: 17, label: "Tarjeta de WhatsAppp" },
  { id: 18, label: "Tarjeta de Instagram" },
  { id: 19, label: "Tarjeta de TikTok" },
  { id: 20, label: "Stickers Google" },
  { id: 21, label: "Stickers Instagram" },
  { id: 22, label: "Stickers WhatsApp" },
  { id: 23, label: "Stickers Sitio Web" },
  { id: 24, label: "Stickers Menú" },
  { id: 25, label: "Stickers Tripadvisor" },
  { id: 26, label: "Stickers Tiktok" },
  { id: 27, label: "DOME Google" },
  { id: 28, label: "DOME Instagram" },
  { id: 29, label: "DOME Menú" },
  { id: 30, label: "Cartel de Google (20x10)" },
  { id: 31, label: "Cartel Menú (7x7)" }
];

  export const nomenclaturas = [
/*     { id: 1, label: "Cupón" },
    { id: 2, label: "Feedback" },
    { id: 3, label: "Listado de enlaces" },
    { id: 4, label: "Ruleta" },
    { id: 5, label: "Página web" },
    { id: 6, label: "Tarjeta de fidelidad" },
    { id: 7, label: "Vcard Plus" }, */
    "FSTG_CG_AAA000",
    "FSTG_CW_00AA000",
    "FSTG_CT_AA1000",
    "FSTG_CF_A1A000",
    "FSTG_CI_1AADOD",
    "FSTG_CB_BBOAD",
    "FSTG_CTT_11AAAO",
    "FSTG_CM_000AAA",
    "FSTG_TG_AA1A000",
    "FSTG_TW_AIAADO",
    "FSTG_TI_Al1A00",
    "FSTG_TTT_AIADADO",
    "FSTG_SG_AAAADO",
    "FSTG_SI_AAAAAO",
    "FSTG_SW_0000AA",
    "FSTG_SSW_00000A",
    "FSTG_SM_AADDAA",
    "FSTG_ST_AOBOOA",
    "FSTG_STT_AGAGAO",
    "FSTG_DG_040000",
    "FSTG_DI_04DADA",
    "FSTG_DM_00A0AO",
    "FSTG_CG(V)_00AA00",
    "FSTG_CM(7cm)_AAA000"
  ];